# Generated by Django 6.0.4 on 2026-04-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='height_ft',
            field=models.FloatField(default=5.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='height_in',
            field=models.FloatField(default=6),
            preserve_default=False,
        ),
    ]
