# Generated by Django 6.0.4 on 2026-04-14 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userstats_height_ft_userstats_height_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='height_ft',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='height_in',
        ),
        migrations.AlterField(
            model_name='userstats',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
