# Generated by Django 6.0.4 on 2026-04-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userstats_height_ft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
