# Generated by Django 6.0.4 on 2026-05-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userstats_activity_alter_userstats_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='bmr',
            field=models.FloatField(default=0),
        ),
    ]
