# Generated by Django 6.0.4 on 2026-05-05 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userstats_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
